<?php

namespace App\Services;

use Prism\Prism\Facades\Prism;
use Prism\Prism\Enums\Provider;
use Prism\Prism\ValueObjects\Messages\UserMessage;
use Illuminate\Support\Facades\Log;
use Prism\Prism\ValueObjects\Messages\AssistantMessage;

/**
 * Service class for interacting with AI models using the Prism library.
 * Handles generating text completions, product descriptions, business insights, and interactive chat.
 */
class AIService
{
    /**
     * The AI provider instance (e.g., Groq, OpenAI).
     */
    private Provider $provider;

    /**
     * The model name to be used for requests (e.g., llama-3.3-70b-versatile).
     */
    private string $model;

    /**
     * Initializes the AIService with default AI provider and model configurations.
     */
    public function __construct()
    {
        // Set Groq as the default AI provider
        $this->provider = Provider::Groq;
        
        // Set the default LLM model
        $this->model = 'llama-3.3-70b-versatile';    
    }

    /**
     * A helper method to send a prompt to the AI provider and get the text response.
     *
     * @param string $systemPrompt Instructions guiding the AI's behavior.
     * @param string $userMessage The input message or query from the user/application.
     * @param int $maxTokens The maximum tokens allowed in the response (default: 500).
     * @return string The text generated by the AI model.
     * @throws \RuntimeException If the AI request fails or is unavailable.
     */
    public function generate(string $systemPrompt, string $userMessage, int $maxTokens = 500)
    {
        try {
            // Call the Prism API using the defined provider, model, prompt, and messages
            $response = Prism::text()
                ->using($this->provider, $this->model)
                ->withSystemPrompt($systemPrompt)
                ->withMaxTokens($maxTokens)
                ->withMessages([
                    new UserMessage($userMessage),
                ])
                ->generate();
            
            return $response->text;
        } catch (\Exception $e) {
            // Log the error for internal tracking and throw a user-friendly exception
            Log::error('AI Service Error: ' . $e->getMessage());
            throw new \RuntimeException('AI service is currently unavailable. Please try again.');
        }
    }

    /**
     * Generates a 1-2 sentence bilingual (Arabic and English) product description.
     *
     * @param string $productName The name of the product.
     * @param float $price The price of the product.
     * @return array An array containing 'ar' (Arabic) and 'en' (English) descriptions.
     */
    public function generateDescription(string $productName, float $price): array
    {
        // Define system guidelines to enforce JSON structure only
        $systemPrompt = 'You are a retail copywriter. Respond with valid JSON only. No explanation, no markdown, no code blocks. Use exactly this structure: {"ar": "Arabic description", "en": "English description"}';

        // Provide the product details for the generation task
        $userMessage = "Write a 1-2 sentence product description for:
Product: {$productName}
Price: {$price} EGP

JSON only: {\"ar\": \"...\", \"en\": \"...\"}";

        // Send the request to the AI model
        $raw = $this->generate($systemPrompt, $userMessage, 300);

        // Strip markdown code blocks (e.g., ```json ... ```) from the response if present
        $cleaned = preg_replace('/^```json\s*|\s*```$/s', '', trim($raw));

        // Attempt to decode the response as JSON
        $decoded = json_decode($cleaned, true);
        if (json_last_error() === JSON_ERROR_NONE) {
            $ar = $decoded['ar'] ?? $decoded['AR'] ?? '';
            $en = $decoded['en'] ?? $decoded['EN'] ?? '';
            if ($ar || $en) {
                return ['ar' => $ar, 'en' => $en];
            }
        }

        // Fallback parsing: check if the model used regex-like "AR: ... EN: ..." format
        if (preg_match('/AR:\s*(.+?)(?=\s*EN:)/s', $raw, $arMatch) &&
            preg_match('/EN:\s*(.+?)$/s', $raw, $enMatch)) {
            return [
                'ar' => trim($arMatch[1]),
                'en' => trim($enMatch[1]),
            ];
        }

        // Final fallback: return the raw response as English description
        return ['ar' => '', 'en' => trim($raw)];
    }

    /**
     * Analyzes sales data for the last 30 days and generates insights.
     * Produces three categories of analysis: Opportunity, Urgent warning, and Trend.
     *
     * @param array $salesData Raw sales data representing transactions or inventory statuses.
     * @param string $tenantName The name of the store owner or tenant (default: 'صاحب المتجر').
     * @return array Structured array with keys 'opportunity', 'urgent', and 'trend'.
     */
    public function generateInsights(array $salesData, string $tenantName = 'صاحب المتجر'): array
    {
        // Set the business analyst system persona
        $systemPrompt = 'أنت محلل أعمال متخصص في تجارة أدوات البناء والأدوات اليدوية في مصر. حلل بيانات المبيعات الفعلية فقط. أجب بـ JSON فقط بدون أي نص إضافي أو markdown.';

        // Encode the sales data to send as context
        $summary = json_encode($salesData, JSON_UNESCAPED_UNICODE);

        // Build the prompt containing the sales data and expected structure
        $userMessage = "بيانات مبيعات متجر {$tenantName} خلال آخر 30 يوم:

{$summary}

أرجع JSON فقط بهذا الشكل بالضبط:
{
  \"opportunity\": {
    \"title\": \"عنوان قصير\",
    \"body\": \"تفسير مختصر بناءً على البيانات\"
  },
  \"urgent\": {
    \"title\": \"عنوان قصير\",
    \"body\": \"تفسير مختصر بناءً على البيانات\"
  },
  \"trend\": {
    \"title\": \"عنوان قصير\",
    \"body\": \"تفسير مختصر بناءً على البيانات\"
  }
}";

        // Call the AI generator with a slightly larger token limit
        $raw = $this->generate($systemPrompt, $userMessage, 600);

        // Strip markdown code blocks if the AI model outputted them
        $cleaned = preg_replace('/^```json\s*|\s*```$/s', '', trim($raw));

        // Decode JSON and verify structure
        $decoded = json_decode($cleaned, true);

        if (json_last_error() === JSON_ERROR_NONE && isset($decoded['opportunity'], $decoded['urgent'], $decoded['trend'])) {
            return $decoded;
        }

        // Fallback structure in case of invalid or unstructured response
        return [
            'opportunity' => ['title' => 'تحليل المبيعات', 'body' => $raw],
            'urgent'      => ['title' => '', 'body' => ''],
            'trend'       => ['title' => '', 'body' => ''],
        ];
    }

    /**
     * Manages an interactive chatbot session, injecting current product and inventory context.
     *
     * @param string $message The latest user message.
     * @param array $history Chat history format: [['role' => 'user'|'assistant', 'content' => '...']].
     * @param int $tenantId The ID of the tenant whose catalog and stock are queried.
     * @return string The chatbot's reply.
     * @throws \RuntimeException If the AI response is empty or fails.
     */
    public function chat(string $message, array $history, int $tenantId): string
    {
        // Retrieve products with inventory details for this specific tenant
        $products = \App\Models\Product::where('tenant_id', $tenantId)
            ->with('inventories')
            ->get();

        // Filter out products where current quantity is less than or equal to the minimum threshold
        $lowStockProducts = $products->filter(function ($product) {
            return $product->inventories->some(
                fn($inv) => $inv->quantity <= $inv->threshold
            );
        });

        // Format the low-stock inventory details for the prompt context
        $lowStockText = $lowStockProducts->isEmpty()
            ? 'لا توجد منتجات منخفضة المخزون حالياً.'
            : $lowStockProducts->map(function ($product) {
                return "- {$product->name}: {$product->inventories->sum('quantity')} وحدة";
            })->join("\n");

        // Format the entire catalog with prices and stock levels
        $catalog = $products->map(function ($product) {
            $totalStock = $product->inventories->sum('quantity');
            return "- {$product->name}: {$totalStock} وحدة (الحد الأدنى: {$product->inventories->min('threshold')}) — السعر: {$product->price} جنيه";  
        })->join("\n");
            
        // Instruct the AI to act as a store assistant with direct access to catalog context
        $systemPrompt = " لا تكرر كلام العميل أو تعيد صياغة سؤاله. اذهب مباشرة للإجابة.أنت مساعد ذكي لمتجر أدوات. ساعد العملاء في الاستفسار عن المنتجات والأسعار والمخزون. كن مختصراً ومفيداً. تحدث بالعربية دائماً.

المنتجات المتاحة حالياً:
{$catalog}

المنتجات المنخفضة المخزون:
{$lowStockText}";

        // Map conversational history into Prism message value objects
        $messages = collect($history)
            ->map(fn($msg) => $msg['role'] === 'user'
                ? new UserMessage($msg['content'])
                : new AssistantMessage($msg['content'])
            )->all();

        // Add the current user message to the conversation array
        $messages[] = new UserMessage($message);

        try {
            // Request the chatbot response using Prism
            $response = Prism::text()
                ->using($this->provider, $this->model)
                ->withSystemPrompt($systemPrompt)
                ->withMaxTokens(300)
                ->withMessages($messages)
                ->generate();

            if (empty($response->text)) {
                throw new \RuntimeException('AI returned empty response.');
            }

            return $response->text;
        } catch (\Exception $e) {
            // Log the error and raise an exception
            Log::error('AI Chat Error: ' . $e->getMessage());
            throw new \RuntimeException('AI service is currently unavailable. Please try again.');
        }
    }
}
